// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd3elRfPIx6cQ1WDRs1c5H97OewlU8oek',
    appId: '1:728947550217:web:f4de03adb74986288db0d8',
    messagingSenderId: '728947550217',
    projectId: 'advmobprog-firebase-93c39',
    authDomain: 'advmobprog-firebase-93c39.firebaseapp.com',
    storageBucket: 'advmobprog-firebase-93c39.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAp0gIYxQRcZJJ29yrN5Lokx8GOhUIjsc',
    appId: '1:728947550217:android:7cb1467871565cf28db0d8',
    messagingSenderId: '728947550217',
    projectId: 'advmobprog-firebase-93c39',
    storageBucket: 'advmobprog-firebase-93c39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlVwIErNs2qeJ-4EM-W25cLjzak2gkZJo',
    appId: '1:728947550217:ios:9cbdaae42cde97c48db0d8',
    messagingSenderId: '728947550217',
    projectId: 'advmobprog-firebase-93c39',
    storageBucket: 'advmobprog-firebase-93c39.firebasestorage.app',
    iosBundleId: 'com.example.macaraigMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBd3elRfPIx6cQ1WDRs1c5H97OewlU8oek',
    appId: '1:728947550217:web:e1cae4e9d752a52b8db0d8',
    messagingSenderId: '728947550217',
    projectId: 'advmobprog-firebase-93c39',
    authDomain: 'advmobprog-firebase-93c39.firebaseapp.com',
    storageBucket: 'advmobprog-firebase-93c39.firebasestorage.app',
  );
}
